"""Initial migration

Revision ID: 5f74bca56a25
Revises: 
Create Date: 2024-12-02 11:11:18.621326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f74bca56a25'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('hash_password', sa.String(), nullable=False),
    sa.Column('notification_frequency', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'SEASONALLY', name='notificationfrequency'), nullable=True),
    sa.Column('preferred_weather_tips', sa.Boolean(), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_table('real_estates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('square_area', sa.Integer(), nullable=False),
    sa.Column('real_estate_type', sa.String(length=50), nullable=False),
    sa.Column('year_built', sa.Integer(), nullable=False),
    sa.Column('insulation_quality', sa.String(length=50), nullable=False),
    sa.Column('energy_source', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weather_based_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('temperature_condition', sa.String(length=100), nullable=False),
    sa.Column('weather_tips', sa.String(length=5000), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('estimated_savings', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('real_estate_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['real_estate_id'], ['real_estates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_message'), 'recommendations', ['message'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendations_message'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_table('weather_based_recommendations')
    op.drop_table('real_estates')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('users')
    # ### end Alembic commands ###
