"""Add user_email to Notification

Revision ID: e9839c4e82a8
Revises: 5f74bca56a25
Create Date: 2024-12-04 14:51:10.731929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9839c4e82a8'
down_revision: Union[str, None] = '5f74bca56a25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('email', sa.String(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'email')
    # ### end Alembic commands ###
